// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2025-02-18 11:46:48.288577639 +0530 IST m=+0.461831462
// using data from
// https://github.com/golang/go/raw/master/CONTRIBUTORS
package project

var Contributors = []string{
}
